// Code generated by protoc-gen-go. DO NOT EDIT.
// source: LPSql.proto

package LPMsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PBSqlParam struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Opt                  int32    `protobuf:"varint,2,opt,name=opt,proto3" json:"opt,omitempty"`
	Table                string   `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Kname                []string `protobuf:"bytes,4,rep,name=kname,proto3" json:"kname,omitempty"`
	Kval                 []string `protobuf:"bytes,5,rep,name=kval,proto3" json:"kval,omitempty"`
	Field                []string `protobuf:"bytes,6,rep,name=field,proto3" json:"field,omitempty"`
	Value                [][]byte `protobuf:"bytes,7,rep,name=value,proto3" json:"value,omitempty"`
	Reply                int32    `protobuf:"varint,8,opt,name=reply,proto3" json:"reply,omitempty"`
	Ret                  bool     `protobuf:"varint,9,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBSqlParam) Reset()         { *m = PBSqlParam{} }
func (m *PBSqlParam) String() string { return proto.CompactTextString(m) }
func (*PBSqlParam) ProtoMessage()    {}
func (*PBSqlParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e75cdce7c3b5e16, []int{0}
}

func (m *PBSqlParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBSqlParam.Unmarshal(m, b)
}
func (m *PBSqlParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBSqlParam.Marshal(b, m, deterministic)
}
func (m *PBSqlParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBSqlParam.Merge(m, src)
}
func (m *PBSqlParam) XXX_Size() int {
	return xxx_messageInfo_PBSqlParam.Size(m)
}
func (m *PBSqlParam) XXX_DiscardUnknown() {
	xxx_messageInfo_PBSqlParam.DiscardUnknown(m)
}

var xxx_messageInfo_PBSqlParam proto.InternalMessageInfo

func (m *PBSqlParam) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PBSqlParam) GetOpt() int32 {
	if m != nil {
		return m.Opt
	}
	return 0
}

func (m *PBSqlParam) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *PBSqlParam) GetKname() []string {
	if m != nil {
		return m.Kname
	}
	return nil
}

func (m *PBSqlParam) GetKval() []string {
	if m != nil {
		return m.Kval
	}
	return nil
}

func (m *PBSqlParam) GetField() []string {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *PBSqlParam) GetValue() [][]byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PBSqlParam) GetReply() int32 {
	if m != nil {
		return m.Reply
	}
	return 0
}

func (m *PBSqlParam) GetRet() bool {
	if m != nil {
		return m.Ret
	}
	return false
}

type UpdateTableGroup struct {
	GroupCount           int32    `protobuf:"varint,1,opt,name=groupCount,proto3" json:"groupCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTableGroup) Reset()         { *m = UpdateTableGroup{} }
func (m *UpdateTableGroup) String() string { return proto.CompactTextString(m) }
func (*UpdateTableGroup) ProtoMessage()    {}
func (*UpdateTableGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e75cdce7c3b5e16, []int{1}
}

func (m *UpdateTableGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTableGroup.Unmarshal(m, b)
}
func (m *UpdateTableGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTableGroup.Marshal(b, m, deterministic)
}
func (m *UpdateTableGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTableGroup.Merge(m, src)
}
func (m *UpdateTableGroup) XXX_Size() int {
	return xxx_messageInfo_UpdateTableGroup.Size(m)
}
func (m *UpdateTableGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTableGroup.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTableGroup proto.InternalMessageInfo

func (m *UpdateTableGroup) GetGroupCount() int32 {
	if m != nil {
		return m.GroupCount
	}
	return 0
}

type EmptyPB struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyPB) Reset()         { *m = EmptyPB{} }
func (m *EmptyPB) String() string { return proto.CompactTextString(m) }
func (*EmptyPB) ProtoMessage()    {}
func (*EmptyPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e75cdce7c3b5e16, []int{2}
}

func (m *EmptyPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyPB.Unmarshal(m, b)
}
func (m *EmptyPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyPB.Marshal(b, m, deterministic)
}
func (m *EmptyPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyPB.Merge(m, src)
}
func (m *EmptyPB) XXX_Size() int {
	return xxx_messageInfo_EmptyPB.Size(m)
}
func (m *EmptyPB) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyPB.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyPB proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PBSqlParam)(nil), "LPMsg.PBSqlParam")
	proto.RegisterType((*UpdateTableGroup)(nil), "LPMsg.UpdateTableGroup")
	proto.RegisterType((*EmptyPB)(nil), "LPMsg.EmptyPB")
}

func init() { proto.RegisterFile("LPSql.proto", fileDescriptor_6e75cdce7c3b5e16) }

var fileDescriptor_6e75cdce7c3b5e16 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x6a, 0x03, 0x21,
	0x10, 0x40, 0xb1, 0xc6, 0x24, 0x3b, 0xed, 0x21, 0x48, 0x0f, 0x73, 0x2a, 0xb2, 0x27, 0x4f, 0x3d,
	0xb4, 0x7f, 0x90, 0x52, 0x7a, 0x49, 0x41, 0x4c, 0xfb, 0x01, 0x86, 0xb5, 0x21, 0xc4, 0x8d, 0xc6,
	0xba, 0x81, 0xfc, 0x5f, 0x3f, 0xac, 0x8c, 0x5e, 0x72, 0x7b, 0xef, 0x31, 0xe0, 0x38, 0x70, 0xbf,
	0x31, 0xdb, 0x73, 0x78, 0x4e, 0x39, 0x96, 0x28, 0xc5, 0xc6, 0x7c, 0xfe, 0xee, 0xfb, 0x3f, 0x06,
	0x60, 0xd6, 0xdb, 0x73, 0x30, 0x2e, 0xbb, 0x51, 0xae, 0x80, 0x4f, 0x87, 0x01, 0x99, 0x62, 0x9a,
	0x5b, 0x42, 0x2a, 0x31, 0x15, 0xbc, 0x53, 0x4c, 0x0b, 0x4b, 0x28, 0x1f, 0x41, 0x14, 0xb7, 0x0b,
	0x1e, 0xb9, 0x62, 0xba, 0xb3, 0x4d, 0xa8, 0x1e, 0x4f, 0x6e, 0xf4, 0x38, 0x53, 0x9c, 0x6a, 0x15,
	0x29, 0x61, 0x76, 0xbc, 0xb8, 0x80, 0xa2, 0xc6, 0xca, 0x34, 0xf9, 0x73, 0xf0, 0x61, 0xc0, 0x79,
	0x9b, 0xac, 0x42, 0xf5, 0xe2, 0xc2, 0xe4, 0x71, 0xa1, 0xb8, 0x7e, 0xb0, 0x4d, 0xa8, 0x66, 0x9f,
	0xc2, 0x15, 0x97, 0xf5, 0xfd, 0x26, 0xb4, 0x53, 0xf6, 0x05, 0x3b, 0xc5, 0xf4, 0xd2, 0x12, 0xf6,
	0x2f, 0xb0, 0xfa, 0x4e, 0x83, 0x2b, 0xfe, 0x8b, 0x96, 0xf9, 0xc8, 0x71, 0x4a, 0xf2, 0x09, 0x60,
	0x4f, 0xf0, 0x16, 0xa7, 0x53, 0xa9, 0x5f, 0x12, 0xf6, 0xa6, 0xf4, 0x1d, 0x2c, 0xde, 0xc7, 0x54,
	0xae, 0x66, 0xbd, 0x9b, 0xd7, 0x9b, 0xbc, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x91, 0x85, 0x3c,
	0x9e, 0x22, 0x01, 0x00, 0x00,
}
