// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LPSql.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "LPSql.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace LPMsg {
class PBSqlParamDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<PBSqlParam>
     _instance;
} _PBSqlParam_default_instance_;
class UpdateTableGroupDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<UpdateTableGroup>
     _instance;
} _UpdateTableGroup_default_instance_;
class EmptyPBDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<EmptyPB>
     _instance;
} _EmptyPB_default_instance_;

namespace protobuf_LPSql_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[3];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSqlParam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSqlParam, uid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSqlParam, opt_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSqlParam, table_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSqlParam, kname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSqlParam, kval_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSqlParam, field_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSqlParam, value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSqlParam, reply_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSqlParam, ret_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateTableGroup, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateTableGroup, groupcount_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EmptyPB, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(PBSqlParam)},
  { 14, -1, sizeof(UpdateTableGroup)},
  { 20, -1, sizeof(EmptyPB)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_PBSqlParam_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_UpdateTableGroup_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_EmptyPB_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "LPSql.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _PBSqlParam_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_PBSqlParam_default_instance_);_UpdateTableGroup_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_UpdateTableGroup_default_instance_);_EmptyPB_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_EmptyPB_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013LPSql.proto\022\005LPMsg\"\214\001\n\nPBSqlParam\022\013\n\003u"
      "id\030\001 \001(\003\022\013\n\003opt\030\002 \001(\005\022\r\n\005table\030\003 \001(\t\022\r\n\005"
      "kname\030\004 \003(\t\022\014\n\004kval\030\005 \003(\t\022\r\n\005field\030\006 \003(\t"
      "\022\r\n\005value\030\007 \003(\014\022\r\n\005reply\030\010 \001(\005\022\013\n\003ret\030\t "
      "\001(\010\"&\n\020UpdateTableGroup\022\022\n\ngroupCount\030\001 "
      "\001(\005\"\t\n\007EmptyPBb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 222);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "LPSql.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_LPSql_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PBSqlParam::kUidFieldNumber;
const int PBSqlParam::kOptFieldNumber;
const int PBSqlParam::kTableFieldNumber;
const int PBSqlParam::kKnameFieldNumber;
const int PBSqlParam::kKvalFieldNumber;
const int PBSqlParam::kFieldFieldNumber;
const int PBSqlParam::kValueFieldNumber;
const int PBSqlParam::kReplyFieldNumber;
const int PBSqlParam::kRetFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PBSqlParam::PBSqlParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_LPSql_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:LPMsg.PBSqlParam)
}
PBSqlParam::PBSqlParam(const PBSqlParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      kname_(from.kname_),
      kval_(from.kval_),
      field_(from.field_),
      value_(from.value_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  table_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.table().size() > 0) {
    table_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_);
  }
  ::memcpy(&uid_, &from.uid_,
    static_cast<size_t>(reinterpret_cast<char*>(&ret_) -
    reinterpret_cast<char*>(&uid_)) + sizeof(ret_));
  // @@protoc_insertion_point(copy_constructor:LPMsg.PBSqlParam)
}

void PBSqlParam::SharedCtor() {
  table_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ret_) -
      reinterpret_cast<char*>(&uid_)) + sizeof(ret_));
  _cached_size_ = 0;
}

PBSqlParam::~PBSqlParam() {
  // @@protoc_insertion_point(destructor:LPMsg.PBSqlParam)
  SharedDtor();
}

void PBSqlParam::SharedDtor() {
  table_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PBSqlParam::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBSqlParam::descriptor() {
  protobuf_LPSql_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_LPSql_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PBSqlParam& PBSqlParam::default_instance() {
  protobuf_LPSql_2eproto::InitDefaults();
  return *internal_default_instance();
}

PBSqlParam* PBSqlParam::New(::google::protobuf::Arena* arena) const {
  PBSqlParam* n = new PBSqlParam;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PBSqlParam::Clear() {
// @@protoc_insertion_point(message_clear_start:LPMsg.PBSqlParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  kname_.Clear();
  kval_.Clear();
  field_.Clear();
  value_.Clear();
  table_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ret_) -
      reinterpret_cast<char*>(&uid_)) + sizeof(ret_));
  _internal_metadata_.Clear();
}

bool PBSqlParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LPMsg.PBSqlParam)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 uid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &uid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 opt = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &opt_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string table = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_table()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->table().data(), static_cast<int>(this->table().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "LPMsg.PBSqlParam.table"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string kname = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_kname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->kname(this->kname_size() - 1).data(),
            static_cast<int>(this->kname(this->kname_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "LPMsg.PBSqlParam.kname"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string kval = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_kval()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->kval(this->kval_size() - 1).data(),
            static_cast<int>(this->kval(this->kval_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "LPMsg.PBSqlParam.kval"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string field = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_field()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->field(this->field_size() - 1).data(),
            static_cast<int>(this->field(this->field_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "LPMsg.PBSqlParam.field"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated bytes value = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 reply = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &reply_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool ret = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &ret_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:LPMsg.PBSqlParam)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LPMsg.PBSqlParam)
  return false;
#undef DO_
}

void PBSqlParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LPMsg.PBSqlParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 uid = 1;
  if (this->uid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->uid(), output);
  }

  // int32 opt = 2;
  if (this->opt() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->opt(), output);
  }

  // string table = 3;
  if (this->table().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->table().data(), static_cast<int>(this->table().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LPMsg.PBSqlParam.table");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->table(), output);
  }

  // repeated string kname = 4;
  for (int i = 0, n = this->kname_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->kname(i).data(), static_cast<int>(this->kname(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LPMsg.PBSqlParam.kname");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->kname(i), output);
  }

  // repeated string kval = 5;
  for (int i = 0, n = this->kval_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->kval(i).data(), static_cast<int>(this->kval(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LPMsg.PBSqlParam.kval");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->kval(i), output);
  }

  // repeated string field = 6;
  for (int i = 0, n = this->field_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->field(i).data(), static_cast<int>(this->field(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LPMsg.PBSqlParam.field");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->field(i), output);
  }

  // repeated bytes value = 7;
  for (int i = 0, n = this->value_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      7, this->value(i), output);
  }

  // int32 reply = 8;
  if (this->reply() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->reply(), output);
  }

  // bool ret = 9;
  if (this->ret() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->ret(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:LPMsg.PBSqlParam)
}

::google::protobuf::uint8* PBSqlParam::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:LPMsg.PBSqlParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 uid = 1;
  if (this->uid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->uid(), target);
  }

  // int32 opt = 2;
  if (this->opt() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->opt(), target);
  }

  // string table = 3;
  if (this->table().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->table().data(), static_cast<int>(this->table().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LPMsg.PBSqlParam.table");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->table(), target);
  }

  // repeated string kname = 4;
  for (int i = 0, n = this->kname_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->kname(i).data(), static_cast<int>(this->kname(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LPMsg.PBSqlParam.kname");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(4, this->kname(i), target);
  }

  // repeated string kval = 5;
  for (int i = 0, n = this->kval_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->kval(i).data(), static_cast<int>(this->kval(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LPMsg.PBSqlParam.kval");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(5, this->kval(i), target);
  }

  // repeated string field = 6;
  for (int i = 0, n = this->field_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->field(i).data(), static_cast<int>(this->field(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LPMsg.PBSqlParam.field");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(6, this->field(i), target);
  }

  // repeated bytes value = 7;
  for (int i = 0, n = this->value_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(7, this->value(i), target);
  }

  // int32 reply = 8;
  if (this->reply() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->reply(), target);
  }

  // bool ret = 9;
  if (this->ret() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(9, this->ret(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LPMsg.PBSqlParam)
  return target;
}

size_t PBSqlParam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LPMsg.PBSqlParam)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated string kname = 4;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->kname_size());
  for (int i = 0, n = this->kname_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->kname(i));
  }

  // repeated string kval = 5;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->kval_size());
  for (int i = 0, n = this->kval_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->kval(i));
  }

  // repeated string field = 6;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->field_size());
  for (int i = 0, n = this->field_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->field(i));
  }

  // repeated bytes value = 7;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->value_size());
  for (int i = 0, n = this->value_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->value(i));
  }

  // string table = 3;
  if (this->table().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->table());
  }

  // int64 uid = 1;
  if (this->uid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->uid());
  }

  // int32 opt = 2;
  if (this->opt() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->opt());
  }

  // int32 reply = 8;
  if (this->reply() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->reply());
  }

  // bool ret = 9;
  if (this->ret() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBSqlParam::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:LPMsg.PBSqlParam)
  GOOGLE_DCHECK_NE(&from, this);
  const PBSqlParam* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PBSqlParam>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:LPMsg.PBSqlParam)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:LPMsg.PBSqlParam)
    MergeFrom(*source);
  }
}

void PBSqlParam::MergeFrom(const PBSqlParam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:LPMsg.PBSqlParam)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  kname_.MergeFrom(from.kname_);
  kval_.MergeFrom(from.kval_);
  field_.MergeFrom(from.field_);
  value_.MergeFrom(from.value_);
  if (from.table().size() > 0) {

    table_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_);
  }
  if (from.uid() != 0) {
    set_uid(from.uid());
  }
  if (from.opt() != 0) {
    set_opt(from.opt());
  }
  if (from.reply() != 0) {
    set_reply(from.reply());
  }
  if (from.ret() != 0) {
    set_ret(from.ret());
  }
}

void PBSqlParam::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:LPMsg.PBSqlParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBSqlParam::CopyFrom(const PBSqlParam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LPMsg.PBSqlParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBSqlParam::IsInitialized() const {
  return true;
}

void PBSqlParam::Swap(PBSqlParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PBSqlParam::InternalSwap(PBSqlParam* other) {
  using std::swap;
  kname_.InternalSwap(&other->kname_);
  kval_.InternalSwap(&other->kval_);
  field_.InternalSwap(&other->field_);
  value_.InternalSwap(&other->value_);
  table_.Swap(&other->table_);
  swap(uid_, other->uid_);
  swap(opt_, other->opt_);
  swap(reply_, other->reply_);
  swap(ret_, other->ret_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PBSqlParam::GetMetadata() const {
  protobuf_LPSql_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_LPSql_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PBSqlParam

// int64 uid = 1;
void PBSqlParam::clear_uid() {
  uid_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 PBSqlParam::uid() const {
  // @@protoc_insertion_point(field_get:LPMsg.PBSqlParam.uid)
  return uid_;
}
void PBSqlParam::set_uid(::google::protobuf::int64 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:LPMsg.PBSqlParam.uid)
}

// int32 opt = 2;
void PBSqlParam::clear_opt() {
  opt_ = 0;
}
::google::protobuf::int32 PBSqlParam::opt() const {
  // @@protoc_insertion_point(field_get:LPMsg.PBSqlParam.opt)
  return opt_;
}
void PBSqlParam::set_opt(::google::protobuf::int32 value) {
  
  opt_ = value;
  // @@protoc_insertion_point(field_set:LPMsg.PBSqlParam.opt)
}

// string table = 3;
void PBSqlParam::clear_table() {
  table_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& PBSqlParam::table() const {
  // @@protoc_insertion_point(field_get:LPMsg.PBSqlParam.table)
  return table_.GetNoArena();
}
void PBSqlParam::set_table(const ::std::string& value) {
  
  table_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LPMsg.PBSqlParam.table)
}
#if LANG_CXX11
void PBSqlParam::set_table(::std::string&& value) {
  
  table_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LPMsg.PBSqlParam.table)
}
#endif
void PBSqlParam::set_table(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  table_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LPMsg.PBSqlParam.table)
}
void PBSqlParam::set_table(const char* value, size_t size) {
  
  table_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LPMsg.PBSqlParam.table)
}
::std::string* PBSqlParam::mutable_table() {
  
  // @@protoc_insertion_point(field_mutable:LPMsg.PBSqlParam.table)
  return table_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* PBSqlParam::release_table() {
  // @@protoc_insertion_point(field_release:LPMsg.PBSqlParam.table)
  
  return table_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void PBSqlParam::set_allocated_table(::std::string* table) {
  if (table != NULL) {
    
  } else {
    
  }
  table_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), table);
  // @@protoc_insertion_point(field_set_allocated:LPMsg.PBSqlParam.table)
}

// repeated string kname = 4;
int PBSqlParam::kname_size() const {
  return kname_.size();
}
void PBSqlParam::clear_kname() {
  kname_.Clear();
}
const ::std::string& PBSqlParam::kname(int index) const {
  // @@protoc_insertion_point(field_get:LPMsg.PBSqlParam.kname)
  return kname_.Get(index);
}
::std::string* PBSqlParam::mutable_kname(int index) {
  // @@protoc_insertion_point(field_mutable:LPMsg.PBSqlParam.kname)
  return kname_.Mutable(index);
}
void PBSqlParam::set_kname(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:LPMsg.PBSqlParam.kname)
  kname_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void PBSqlParam::set_kname(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:LPMsg.PBSqlParam.kname)
  kname_.Mutable(index)->assign(std::move(value));
}
#endif
void PBSqlParam::set_kname(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  kname_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:LPMsg.PBSqlParam.kname)
}
void PBSqlParam::set_kname(int index, const char* value, size_t size) {
  kname_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:LPMsg.PBSqlParam.kname)
}
::std::string* PBSqlParam::add_kname() {
  // @@protoc_insertion_point(field_add_mutable:LPMsg.PBSqlParam.kname)
  return kname_.Add();
}
void PBSqlParam::add_kname(const ::std::string& value) {
  kname_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:LPMsg.PBSqlParam.kname)
}
#if LANG_CXX11
void PBSqlParam::add_kname(::std::string&& value) {
  kname_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:LPMsg.PBSqlParam.kname)
}
#endif
void PBSqlParam::add_kname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  kname_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:LPMsg.PBSqlParam.kname)
}
void PBSqlParam::add_kname(const char* value, size_t size) {
  kname_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:LPMsg.PBSqlParam.kname)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
PBSqlParam::kname() const {
  // @@protoc_insertion_point(field_list:LPMsg.PBSqlParam.kname)
  return kname_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
PBSqlParam::mutable_kname() {
  // @@protoc_insertion_point(field_mutable_list:LPMsg.PBSqlParam.kname)
  return &kname_;
}

// repeated string kval = 5;
int PBSqlParam::kval_size() const {
  return kval_.size();
}
void PBSqlParam::clear_kval() {
  kval_.Clear();
}
const ::std::string& PBSqlParam::kval(int index) const {
  // @@protoc_insertion_point(field_get:LPMsg.PBSqlParam.kval)
  return kval_.Get(index);
}
::std::string* PBSqlParam::mutable_kval(int index) {
  // @@protoc_insertion_point(field_mutable:LPMsg.PBSqlParam.kval)
  return kval_.Mutable(index);
}
void PBSqlParam::set_kval(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:LPMsg.PBSqlParam.kval)
  kval_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void PBSqlParam::set_kval(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:LPMsg.PBSqlParam.kval)
  kval_.Mutable(index)->assign(std::move(value));
}
#endif
void PBSqlParam::set_kval(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  kval_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:LPMsg.PBSqlParam.kval)
}
void PBSqlParam::set_kval(int index, const char* value, size_t size) {
  kval_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:LPMsg.PBSqlParam.kval)
}
::std::string* PBSqlParam::add_kval() {
  // @@protoc_insertion_point(field_add_mutable:LPMsg.PBSqlParam.kval)
  return kval_.Add();
}
void PBSqlParam::add_kval(const ::std::string& value) {
  kval_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:LPMsg.PBSqlParam.kval)
}
#if LANG_CXX11
void PBSqlParam::add_kval(::std::string&& value) {
  kval_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:LPMsg.PBSqlParam.kval)
}
#endif
void PBSqlParam::add_kval(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  kval_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:LPMsg.PBSqlParam.kval)
}
void PBSqlParam::add_kval(const char* value, size_t size) {
  kval_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:LPMsg.PBSqlParam.kval)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
PBSqlParam::kval() const {
  // @@protoc_insertion_point(field_list:LPMsg.PBSqlParam.kval)
  return kval_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
PBSqlParam::mutable_kval() {
  // @@protoc_insertion_point(field_mutable_list:LPMsg.PBSqlParam.kval)
  return &kval_;
}

// repeated string field = 6;
int PBSqlParam::field_size() const {
  return field_.size();
}
void PBSqlParam::clear_field() {
  field_.Clear();
}
const ::std::string& PBSqlParam::field(int index) const {
  // @@protoc_insertion_point(field_get:LPMsg.PBSqlParam.field)
  return field_.Get(index);
}
::std::string* PBSqlParam::mutable_field(int index) {
  // @@protoc_insertion_point(field_mutable:LPMsg.PBSqlParam.field)
  return field_.Mutable(index);
}
void PBSqlParam::set_field(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:LPMsg.PBSqlParam.field)
  field_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void PBSqlParam::set_field(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:LPMsg.PBSqlParam.field)
  field_.Mutable(index)->assign(std::move(value));
}
#endif
void PBSqlParam::set_field(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  field_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:LPMsg.PBSqlParam.field)
}
void PBSqlParam::set_field(int index, const char* value, size_t size) {
  field_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:LPMsg.PBSqlParam.field)
}
::std::string* PBSqlParam::add_field() {
  // @@protoc_insertion_point(field_add_mutable:LPMsg.PBSqlParam.field)
  return field_.Add();
}
void PBSqlParam::add_field(const ::std::string& value) {
  field_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:LPMsg.PBSqlParam.field)
}
#if LANG_CXX11
void PBSqlParam::add_field(::std::string&& value) {
  field_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:LPMsg.PBSqlParam.field)
}
#endif
void PBSqlParam::add_field(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  field_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:LPMsg.PBSqlParam.field)
}
void PBSqlParam::add_field(const char* value, size_t size) {
  field_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:LPMsg.PBSqlParam.field)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
PBSqlParam::field() const {
  // @@protoc_insertion_point(field_list:LPMsg.PBSqlParam.field)
  return field_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
PBSqlParam::mutable_field() {
  // @@protoc_insertion_point(field_mutable_list:LPMsg.PBSqlParam.field)
  return &field_;
}

// repeated bytes value = 7;
int PBSqlParam::value_size() const {
  return value_.size();
}
void PBSqlParam::clear_value() {
  value_.Clear();
}
const ::std::string& PBSqlParam::value(int index) const {
  // @@protoc_insertion_point(field_get:LPMsg.PBSqlParam.value)
  return value_.Get(index);
}
::std::string* PBSqlParam::mutable_value(int index) {
  // @@protoc_insertion_point(field_mutable:LPMsg.PBSqlParam.value)
  return value_.Mutable(index);
}
void PBSqlParam::set_value(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:LPMsg.PBSqlParam.value)
  value_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void PBSqlParam::set_value(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:LPMsg.PBSqlParam.value)
  value_.Mutable(index)->assign(std::move(value));
}
#endif
void PBSqlParam::set_value(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  value_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:LPMsg.PBSqlParam.value)
}
void PBSqlParam::set_value(int index, const void* value, size_t size) {
  value_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:LPMsg.PBSqlParam.value)
}
::std::string* PBSqlParam::add_value() {
  // @@protoc_insertion_point(field_add_mutable:LPMsg.PBSqlParam.value)
  return value_.Add();
}
void PBSqlParam::add_value(const ::std::string& value) {
  value_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:LPMsg.PBSqlParam.value)
}
#if LANG_CXX11
void PBSqlParam::add_value(::std::string&& value) {
  value_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:LPMsg.PBSqlParam.value)
}
#endif
void PBSqlParam::add_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  value_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:LPMsg.PBSqlParam.value)
}
void PBSqlParam::add_value(const void* value, size_t size) {
  value_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:LPMsg.PBSqlParam.value)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
PBSqlParam::value() const {
  // @@protoc_insertion_point(field_list:LPMsg.PBSqlParam.value)
  return value_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
PBSqlParam::mutable_value() {
  // @@protoc_insertion_point(field_mutable_list:LPMsg.PBSqlParam.value)
  return &value_;
}

// int32 reply = 8;
void PBSqlParam::clear_reply() {
  reply_ = 0;
}
::google::protobuf::int32 PBSqlParam::reply() const {
  // @@protoc_insertion_point(field_get:LPMsg.PBSqlParam.reply)
  return reply_;
}
void PBSqlParam::set_reply(::google::protobuf::int32 value) {
  
  reply_ = value;
  // @@protoc_insertion_point(field_set:LPMsg.PBSqlParam.reply)
}

// bool ret = 9;
void PBSqlParam::clear_ret() {
  ret_ = false;
}
bool PBSqlParam::ret() const {
  // @@protoc_insertion_point(field_get:LPMsg.PBSqlParam.ret)
  return ret_;
}
void PBSqlParam::set_ret(bool value) {
  
  ret_ = value;
  // @@protoc_insertion_point(field_set:LPMsg.PBSqlParam.ret)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UpdateTableGroup::kGroupCountFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UpdateTableGroup::UpdateTableGroup()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_LPSql_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:LPMsg.UpdateTableGroup)
}
UpdateTableGroup::UpdateTableGroup(const UpdateTableGroup& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  groupcount_ = from.groupcount_;
  // @@protoc_insertion_point(copy_constructor:LPMsg.UpdateTableGroup)
}

void UpdateTableGroup::SharedCtor() {
  groupcount_ = 0;
  _cached_size_ = 0;
}

UpdateTableGroup::~UpdateTableGroup() {
  // @@protoc_insertion_point(destructor:LPMsg.UpdateTableGroup)
  SharedDtor();
}

void UpdateTableGroup::SharedDtor() {
}

void UpdateTableGroup::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UpdateTableGroup::descriptor() {
  protobuf_LPSql_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_LPSql_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UpdateTableGroup& UpdateTableGroup::default_instance() {
  protobuf_LPSql_2eproto::InitDefaults();
  return *internal_default_instance();
}

UpdateTableGroup* UpdateTableGroup::New(::google::protobuf::Arena* arena) const {
  UpdateTableGroup* n = new UpdateTableGroup;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void UpdateTableGroup::Clear() {
// @@protoc_insertion_point(message_clear_start:LPMsg.UpdateTableGroup)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  groupcount_ = 0;
  _internal_metadata_.Clear();
}

bool UpdateTableGroup::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LPMsg.UpdateTableGroup)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 groupCount = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &groupcount_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:LPMsg.UpdateTableGroup)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LPMsg.UpdateTableGroup)
  return false;
#undef DO_
}

void UpdateTableGroup::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LPMsg.UpdateTableGroup)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 groupCount = 1;
  if (this->groupcount() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->groupcount(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:LPMsg.UpdateTableGroup)
}

::google::protobuf::uint8* UpdateTableGroup::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:LPMsg.UpdateTableGroup)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 groupCount = 1;
  if (this->groupcount() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->groupcount(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LPMsg.UpdateTableGroup)
  return target;
}

size_t UpdateTableGroup::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LPMsg.UpdateTableGroup)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 groupCount = 1;
  if (this->groupcount() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->groupcount());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UpdateTableGroup::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:LPMsg.UpdateTableGroup)
  GOOGLE_DCHECK_NE(&from, this);
  const UpdateTableGroup* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UpdateTableGroup>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:LPMsg.UpdateTableGroup)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:LPMsg.UpdateTableGroup)
    MergeFrom(*source);
  }
}

void UpdateTableGroup::MergeFrom(const UpdateTableGroup& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:LPMsg.UpdateTableGroup)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.groupcount() != 0) {
    set_groupcount(from.groupcount());
  }
}

void UpdateTableGroup::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:LPMsg.UpdateTableGroup)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UpdateTableGroup::CopyFrom(const UpdateTableGroup& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LPMsg.UpdateTableGroup)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateTableGroup::IsInitialized() const {
  return true;
}

void UpdateTableGroup::Swap(UpdateTableGroup* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UpdateTableGroup::InternalSwap(UpdateTableGroup* other) {
  using std::swap;
  swap(groupcount_, other->groupcount_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata UpdateTableGroup::GetMetadata() const {
  protobuf_LPSql_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_LPSql_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// UpdateTableGroup

// int32 groupCount = 1;
void UpdateTableGroup::clear_groupcount() {
  groupcount_ = 0;
}
::google::protobuf::int32 UpdateTableGroup::groupcount() const {
  // @@protoc_insertion_point(field_get:LPMsg.UpdateTableGroup.groupCount)
  return groupcount_;
}
void UpdateTableGroup::set_groupcount(::google::protobuf::int32 value) {
  
  groupcount_ = value;
  // @@protoc_insertion_point(field_set:LPMsg.UpdateTableGroup.groupCount)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EmptyPB::EmptyPB()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_LPSql_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:LPMsg.EmptyPB)
}
EmptyPB::EmptyPB(const EmptyPB& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:LPMsg.EmptyPB)
}

void EmptyPB::SharedCtor() {
  _cached_size_ = 0;
}

EmptyPB::~EmptyPB() {
  // @@protoc_insertion_point(destructor:LPMsg.EmptyPB)
  SharedDtor();
}

void EmptyPB::SharedDtor() {
}

void EmptyPB::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* EmptyPB::descriptor() {
  protobuf_LPSql_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_LPSql_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const EmptyPB& EmptyPB::default_instance() {
  protobuf_LPSql_2eproto::InitDefaults();
  return *internal_default_instance();
}

EmptyPB* EmptyPB::New(::google::protobuf::Arena* arena) const {
  EmptyPB* n = new EmptyPB;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void EmptyPB::Clear() {
// @@protoc_insertion_point(message_clear_start:LPMsg.EmptyPB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool EmptyPB::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LPMsg.EmptyPB)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:LPMsg.EmptyPB)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LPMsg.EmptyPB)
  return false;
#undef DO_
}

void EmptyPB::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LPMsg.EmptyPB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:LPMsg.EmptyPB)
}

::google::protobuf::uint8* EmptyPB::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:LPMsg.EmptyPB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LPMsg.EmptyPB)
  return target;
}

size_t EmptyPB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LPMsg.EmptyPB)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void EmptyPB::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:LPMsg.EmptyPB)
  GOOGLE_DCHECK_NE(&from, this);
  const EmptyPB* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const EmptyPB>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:LPMsg.EmptyPB)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:LPMsg.EmptyPB)
    MergeFrom(*source);
  }
}

void EmptyPB::MergeFrom(const EmptyPB& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:LPMsg.EmptyPB)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void EmptyPB::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:LPMsg.EmptyPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EmptyPB::CopyFrom(const EmptyPB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LPMsg.EmptyPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EmptyPB::IsInitialized() const {
  return true;
}

void EmptyPB::Swap(EmptyPB* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EmptyPB::InternalSwap(EmptyPB* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata EmptyPB::GetMetadata() const {
  protobuf_LPSql_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_LPSql_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// EmptyPB

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace LPMsg

// @@protoc_insertion_point(global_scope)
