// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: define.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "define.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace LPMsg {

namespace protobuf_define_2eproto {


namespace {

const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;
namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "define.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      NULL, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014define.proto\022\005LPMsg*\361\002\n\014LP_CM_MSG_ID\022\017"
      "\n\013CM_MSG_NONE\020\000\022\r\n\010CM_BEGAN\020\220N\022\r\n\010CM_LOG"
      "IN\020\221N\022\022\n\rCM_ENTER_ROOM\020\222N\022\023\n\016CM_CREATE_R"
      "OLE\020\223N\022\023\n\016CM_BEGIN_MATCH\020\224N\022\022\n\rCM_STOP_M"
      "ATCH\020\225N\022\032\n\025CM_ENTER_BATTLE_SCENE\020\226N\022\030\n\023C"
      "M_PLAYER_OPERATION\020\227N\022\021\n\014CM_FIX_FRAME\020\230N"
      "\022\022\n\rCM_ENTER_GAME\020\231N\022\025\n\020CM_SEARCH_PLAYER"
      "\020\232N\022\022\n\rCM_ADD_FRIEND\020\233N\022\030\n\023CM_OPT_FRIEND"
      "_APPLY\020\234N\022\025\n\020CM_DELETE_FRIEND\020\235N\022\032\n\025CM_S"
      "YNC_RELATION_INFO\020\236N\022\013\n\006CM_END\020\230u*\332\002\n\014LP"
      "_SM_MSG_ID\022\017\n\013SM_MSG_NONE\020\000\022\r\n\010SM_BEGIN\020"
      "\230u\022\021\n\014SM_LOGIN_RES\020\231u\022\022\n\rSM_ENTER_ROOM\020\232"
      "u\022\023\n\016SM_CREATE_ROLE\020\233u\022\023\n\016SM_MATCH_STATE"
      "\020\234u\022\024\n\017SM_ENTER_BATTLE\020\235u\022\030\n\023SM_PLAYER_O"
      "PERATION\020\236u\022\023\n\016SM_OBJECT_INFO\020\237u\022\026\n\021SM_S"
      "ELF_ROLE_INFO\020\240u\022\026\n\021SM_OPERATION_SIZE\020\241u"
      "\022\023\n\016SM_OBJECT_SIZE\020\242u\022\027\n\022SM_OLD_BATTLE_I"
      "NFO\020\243u\022\021\n\014SM_FIX_FRAME\020\244u\022\025\n\020SM_RELATION"
      "_INFO\020\245u\022\014\n\006SM_END\020\240\234\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 750);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "define.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_define_2eproto

const ::google::protobuf::EnumDescriptor* LP_CM_MSG_ID_descriptor() {
  protobuf_define_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_define_2eproto::file_level_enum_descriptors[0];
}
bool LP_CM_MSG_ID_IsValid(int value) {
  switch (value) {
    case 0:
    case 10000:
    case 10001:
    case 10002:
    case 10003:
    case 10004:
    case 10005:
    case 10006:
    case 10007:
    case 10008:
    case 10009:
    case 10010:
    case 10011:
    case 10012:
    case 10013:
    case 10014:
    case 15000:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* LP_SM_MSG_ID_descriptor() {
  protobuf_define_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_define_2eproto::file_level_enum_descriptors[1];
}
bool LP_SM_MSG_ID_IsValid(int value) {
  switch (value) {
    case 0:
    case 15000:
    case 15001:
    case 15002:
    case 15003:
    case 15004:
    case 15005:
    case 15006:
    case 15007:
    case 15008:
    case 15009:
    case 15010:
    case 15011:
    case 15012:
    case 15013:
    case 20000:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace LPMsg

// @@protoc_insertion_point(global_scope)
