#ifndef SERVER_MSG_DEFINE_H
#define SERVER_MSG_DEFINE_H

#include "MsgDefine.h"

enum LAYER_MSG
{
	L_MSG_BEGIN = L_END_BEFOR,

	L_DB_SQL_OPERATION,
	L_DB_SAVE_ALL_PLAYER,


	L_MSG_END = L_END,
};

enum SERVER_MSG
{
	N_SERVER_MSG_BEGAN = N_END_BEFOR,

	//----------- to mysql --------------

	N_TDB_SQL_OPERATION,


	//----------- to mysql <<<<<<<<<<<<<<<<<<

	//----------- to room --------------

	N_TROM_GET_ROLE_LIST = 502,
	N_TROM_LOAD_ROLE_DATA = 503,
	N_TROM_DB_PLAYER_OPERATION = 504,
	N_TROM_ASK_ADD_FRIEND = 505,
	N_TROM_TEAM_INFO = 506,
	N_TROM_TEAM_DISBAND = 507,

	// room lua 650 - 700

	//----------- to room <<<<<<<<<<<<<<

	//----------- to room manager --------------

	N_TRMM_PLAYER_ONLINE = 704,
	N_TRMM_PLAYER_LOGOUT = 705,
	N_TRMM_CHECK_PLAYER_ONLINE = 706,
	N_TRMM_TRANS_MSG_TO_PLAYER = 707,

	//----------- to room manager <<<<<<<<<<<<

	//----------- to team ---------------

	N_TEAM_CREATE_TEAM = 901,
	N_TEAM_JOIN_TEAM = 902,
	N_TEAM_QUIT_TEAM = 903,
	N_TEAM_DISBAND_TEAM = 904,

	//----------- to team <<<<<<<<<<<<<<<

	N_REQ_NOTICE_SERVER,
	N_ACK_NOTICE_SERVER,

	N_ACK_SERVER_ONLINE,
	N_ACK_SERVER_OFFLINE,

	N_REQ_GET_MATCH_SERVER,
	N_ACK_GET_MATCH_SERVER,

	N_ACK_BATTLE_FREE_SCENE,

	N_REQ_MATCH_BATTLE,
	N_ACK_MATCH_BATTLE,

	N_REQ_BEGIN_BATTLE_SCENE,
	N_REQ_BATTLE_ADD_PLAYER,
	N_ACK_BATTLE_ADD_PLAYER,

	N_ACK_OBJECT_INFO_ENTER_VIEW,
	N_ACK_SCENE_AOI_UPDATE,
	N_ACK_FINISH_FRAME,
	N_ACK_BATTLE_SCENE_OVER,
	N_ACK_SELF_ROLE_INFO,

	N_SERVER_MSG_END = 2000,
};

enum WEB_MSG
{
	N_WEB_BEGIN = 2000,
	N_WEB_TEST = 2001,
	N_WEB_TEST2 = 2002,
	N_WBE_TEST2 = 2002,
	N_WBE_ON_RESPONSE = 2003,
	N_WBE_REQUEST_1 = 2004,
	N_WEB_END = N_END,
};


#endif