#ifndef SERVER_MSG_DEFINE_H
#define SERVER_MSG_DEFINE_H

enum SERVER_MSG
{
	N_SERVER_MSG_BEGAN = 1000,

	N_REQ_NOTICE_SERVER,
	N_ACK_NOTICE_SERVER,

	N_ACK_SERVER_ONLINE,
	N_ACK_SERVER_OFFLINE,

	N_REQ_GET_MATCH_SERVER,
	N_ACK_GET_MATCH_SERVER,

	N_ACK_BATTLE_FREE_SCENE,

	N_REQ_MATCH_BATTLE,
	N_ACK_MATCH_BATTLE,

	N_REQ_BEGIN_BATTLE_SCENE,
	N_REQ_BATTLE_ADD_PLAYER,
	N_ACK_BATTLE_ADD_PLAYER,

	N_ACK_OBJECT_INFO_ENTER_VIEW,
	N_ACK_SCENE_AOI_UPDATE,
	N_ACK_FINISH_FRAME,
	N_ACK_BATTLE_SCENE_OVER,

	N_SERVER_MSG_END,
};


#endif