require("util.msg_enum")

CTOL = {
	CTOL_NET_MSG = 1,
	CTOL_MSG = 2,
	CTOL_SET_PLAYER_GATE_INFO = 11,
	CTOL_PLAYER_OFFLINE = 12,
	CTOL_FRAME_UPDATE = 13,
}

LTOC = {
	LTOC_SEND_MSG = 1,
	LTOC_SEND_SERVER = 2,
	LTOC_DO_SQL_OPERATION = 101,
	LTOC_SQL_UPDATE_PLAYER_DATA = 102,
	LTOC_SQL_DELETE_PLAYER_DATA = 103,
	LTOC_SEND_MSG_TO_PLAYER = 104,
	LTOC_DO_SQL_OPERATION_PROTO = 105,
}

SERVER_TYPE = {
	ST_ROOM = 8,
	ST_ROOM_MANAGER = 9,
	ST_TEAM = 15,
	ST_TEAM_PROXY = 18,
}

SQL_OPRATION = {
	SOP_NONE = 0,
	SOP_ROLE_SELET = 1,
	SOP_CREATE_ROLE = 2,
	SOP_LOAD_PLAYER_DATA = 3,
	SOP_UPDATE_PLAYER_DATA = 4,
	SOP_DELETE_PLAYER_DATA = 5,
	SOP_SEARCH_PLAYER = 6,
	SOP_SAVE_PlAYER_TO_DB = 7,
}